baseURL = "http://tomkral.eu/newblog/"
languageCode = "en"
title = "Tomas Kral"

theme = "hyde"

defaultContentLanguageInSubdir = true
DefaultContentLanguage = "en"

[params]
    themeColor = "theme-base-0d"
    description = " "

[Languages]

[Languages.en]
    weight = 1
    description = "nothing interesting here"

[Languages.cz]
    weight = 2
    description = "nic moc zajímavého"

