baseURL = "http://tomkral.eu"
languageCode = "en"
title = "Tomas Kral"

theme = "hyde"

defaultContentLanguageInSubdir = true
DefaultContentLanguage = "en"

preserveTaxonomyNames = true
# [taxonomies]
#     tag = "tags"
#     category = "categories"

[params]
    themeColor = "theme-base-0d"
    description = " "
    github = "kadel"
    twitter = "kadel"
    facebook = "tomas.kral"
    linkedin = "kraltomas"

[Languages]

[Languages.en]
    LanguageName = "english"
    weight = 1
    description = "nothing interesting here"
    DateFormat =  "01/02/2006"

[Languages.cs]
    LanguageName = "czech"
    weight = 2
    title = "Tomáš Král"
    description = "nic moc zajímavého"
    DateFormat =  "02.01.2006"
