baseURL = "http://tomkral.eu/newblog/"
languageCode = "en"
title = "Tomas Kral"

theme = "hyde"

defaultContentLanguageInSubdir = true
DefaultContentLanguage = "en"

[params]
    themeColor = "theme-base-0d"
    description = " "

[Languages]

[Languages.en]
    LanguageName = "english"
    weight = 1
    description = "nothing interesting here"
    DateFormat =  "01/02/2006"

[Languages.cs]
    LanguageName = "czech"
    weight = 2
    description = "nic moc zajímavého"
    DateFormat =  "02.01.2006"
